# -*- coding: utf-8 -*-
"""rotacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MWciNG1ZZPjcJ7EAA0-5wt4MljSKM6PY
"""

import numpy as np,math


def rot_x(x, y, z, theta):
    '''
    rota un vector en el eje x utilizando sus coordenadas y un angulo

    Parameters:
        x (float): valor del vector en el eje x
        y (float): valor del vector en el eje y
        z (float): valor del vector en el eje z
        theta (float): valor del angulo en grados

    Returns:
        numpy.ndarray: el vector ya rotado

    '''
    rad = math.radians(theta)
    vector = np.array([x,y,z])
    matrizX = np.array([[1,0,0],[0,math.cos(rad),- math.sin(rad)],[0,math.sin(rad),math.cos(rad)]])
    return matrizX @ vector

    pass


def rot_y(x, y, z, theta):
    '''
    rota un vector en el eje y utilizando sus coordenadas y un angulo

    Parameters:
        x (float): valor del vector en el eje x
        y (float): valor del vector en el eje y
        z (float): valor del vector en el eje z
        theta (float): valor del angulo en grados

    Returns:
        numpy.ndarray: el vector ya rotado
    '''
    rad = math.radians(theta)
    vector = np.array([x,y,z])
    matrizY = np.array([[math.cos(rad),0,math.sin(rad)],[0,1,0],[- math.sin(rad),0,math.cos(rad)]])
    return matrizY @ vector
    pass

def rot_z(x, y, z, theta):
    '''
    rota un vector en el eje z utilizando sus coordenadas y un angulo

    Parameters:
        x (float): valor del vector en el eje x
        y (float): valor del vector en el eje y
        z (float): valor del vector en el eje z
        theta (float): valor del angulo en grados

    Returns:
        numpy.ndarray: el vector ya rotado
    '''
    rad = math.radians(theta)
    vector = np.array([x,y,z])
    matrizZ = np.array([[math.cos(rad),- math.sin(rad),0],[math.sin(rad),math.cos(rad),0],[0,0,1]])
    return matrizZ @ vector
    pass


def rotar(x, y, z, theta, axis):
    '''
    recibe los datos del vector para decidir en que eje rotarlo

    Parameters:
        x (float): valor del vector en el eje x
        y (float): valor del vector en el eje y
        z (float): valor del vector en el eje z
        theta (float): valor del angulo en grados
        axis (string): Angulo en el que se rotara el vector

    Returns:
        numpy.ndarray: el vector ya rotado
    '''

    if(axis == "X"):
      resultado = rot_x(x,y,z,theta)
    elif (axis == "Y"):
      resultado = rot_y(x,y,z,theta)
    else:
      resultado = rot_z(x,y,z,theta)

    return resultado


    pass


entrada = input("Escriba las 3 coordenadas del vector separadas por un espacio: ")
angulo = float(input("Escriba el angulo en que se va a rotar el vector (en grados): "))
eje = input("Escriba el eje en el que se rotara el vector (X - Y - Z):")
lista = entrada.split(' ')
x = float(lista[0])
y = float(lista[1])
z = float(lista[2])


print(rotar(x,y,z,angulo,eje))